Add unit tests for us.codecraft.webmagic.utils.NumberUtils
Diffblue-benchmarks/Code4craft-webmagic pull request #1
Opened 2019-07-29 15:03 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `us.codecraft.webmagic.utils.NumberUtils` in the `webmagic-core` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-07-29 16:35 UTC, petersear requested changes
Looking at the other test file in the same directory, UrlUtilsTest.java, the indents seem to be spaces whereas here they are tabs.
Also, they have used the test name format `testMethodName()` and combined all asserts for the same method into one test method. You could combine the 5 asserts here into 1 test method called `testCompareLong()`

2019-07-29 16:35 UTC, petersear commented on webmagic-core/src/test/java/us/codecraft/webmagic/utils/NumberUtilsTest.java
> +	@Test public void compareLongInputZero() {
`@Test` should be on separate line (applies to all tests)

2019-07-30 09:55 UTC, paulkennethkent approved these changes

2019-07-30 10:39 UTC, petersear approved these changes

2019-09-04 08:38 UTC, closed without merging